### PR TITLE
Issues #87 #104 prepare nuxeo upgrade

### PR DESCRIPTION
**Pull request by jcarsique**
The whole build was successfully validated, without running the tests.
Could you check before merging that the build result is fine too ?

### CODE REVIEW

**Comment by mkalam-alami** [comment]
I had to change a few lines to the buildr script but it works fine otherwise.
(PS: Did you use a specific tool to do the Maven refactoring?)

**Comment by mkalam-alami** [comment]
Sorry I went over this a bit quickly, several servers don't launch anymore in the EasySOA distribution. I'm investigating.

**Comment by jcarsique** [comment]
What is the current status about the servers start?
Maybe I should work on packaging the Nuxeo server? You will need a Nuxeo DM server and activating the DM module on a CAP server can easily be automated. Did you encountered that issue too?

**Comment by mkalam-alami** [comment]
Regarding Nuxeo itself, the bundles are actually working ; now while it's not urgent, it would be interesting indeed to take advantage of your automated packaging scripts. We have quickly mentioned this idea with @tiry during the workshop, why not give a try once the FraSCAti refactoring is done! Thanks for the suggestion.

Right know I'm battling with some dependency problems/classpath issues, mainly with the Apache CXF servers we have. I'll send you a detailed mail regarding these issues tomorrow morning.

**Pull request merged**
